export enum Color {
  BUTTON_ACCENT_PRIMARY = "#E33203",
  BUTTON_ACCENT_SECONDARY = "#7F7F7F",
  BUTTON_PRIMARY = "#FD744F",
  BUTTON_SECONDARY = "#B1B1B1",

  BUTTON_TEXT_PRIMARY = "#FFFFFF",

  HEADER_TEXT_PRIMARY = "#E33203",
  HEADER_TEXT_SECONDARY = "#000000",

  INPUT_BACKGROUND_PRIMARY = "#F2F2F2",
  PLAIN_TEXT_PRIMARY = "#000000",

  PLAIN_TEXT_SECONDARY = "#9D9D9D",
}
